"""Add max exp

Revision ID: 81ad43380751
Revises: ef9edc9d40a5
Create Date: 2024-09-08 23:22:39.020962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ad43380751'
down_revision = 'ef9edc9d40a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_exp', sa.Integer(), nullable=True))

    # Then update NULL values to 0
    op.execute('UPDATE user SET max_exp = 100 WHERE max_exp IS NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('max_exp')

    # ### end Alembic commands ###
